name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

# Concurrency controls to prevent multiple builds on the same branch/PR
# This saves costs by canceling outdated builds when new commits are pushed
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

jobs:
  # Quick formatting and linting checks
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Set up Rust cache
        uses: Swatinem/rust-cache@v2
        with:
          prefix-key: "check"

      - name: Check formatting
        run: cargo fmt --all -- --check

      - name: Run clippy
        run: cargo clippy --all-targets --all-features -- -D warnings

      - name: Check cargo check
        run: cargo check --all-targets --all-features

  # Main test suite
  test:
    name: Test Suite
    runs-on: ${{ matrix.os }}
    needs: check
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        rust: [stable, beta]
        include:
          # Test nightly only on Ubuntu to reduce costs
          - os: ubuntu-latest
            rust: nightly
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}

      - name: Set up Rust cache
        uses: Swatinem/rust-cache@v2
        with:
          prefix-key: "test-${{ matrix.os }}-${{ matrix.rust }}"

      - name: Run unit tests
        run: cargo test --lib --bins
        env:
          RUST_LOG: debug

      - name: Run integration tests
        run: cargo test --test '*'
        env:
          RUST_LOG: debug

  # Security audit
  audit:
    name: Security Audit
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Install cargo-audit
        run: cargo install cargo-audit

      - name: Run security audit
        run: cargo audit

  # Build release binaries
  build:
    name: Build Release
    runs-on: ${{ matrix.os }}
    needs: test
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Set up Rust cache
        uses: Swatinem/rust-cache@v2
        with:
          prefix-key: "build-${{ matrix.os }}"

      - name: Build release binary
        run: cargo build --release --bin runcept

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: runcept-${{ matrix.os }}
          path: |
            target/release/runcept${{ matrix.os == 'windows-latest' && '.exe' || '' }}

  # Coverage report (only on main branch to save costs)
  coverage:
    name: Coverage
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: llvm-tools-preview

      - name: Set up Rust cache
        uses: Swatinem/rust-cache@v2
        with:
          prefix-key: "coverage"

      - name: Install cargo-llvm-cov
        run: cargo install cargo-llvm-cov

      - name: Run coverage
        run: cargo llvm-cov --html --all-targets --workspace
        env:
          RUST_LOG: debug

      - name: Upload coverage reports
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: target/llvm-cov/html/

  # Documentation check
  docs:
    name: Documentation
    runs-on: ubuntu-latest
    needs: check
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Set up Rust cache
        uses: Swatinem/rust-cache@v2
        with:
          prefix-key: "docs"

      - name: Check documentation
        run: cargo doc --no-deps --document-private-items --workspace
        env:
          RUSTDOCFLAGS: -D warnings