name: Release Please

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      tag_name: ${{ steps.release.outputs.tag_name }}
    steps:
      - name: Generate GitHub App Token
        id: app-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.REPOSITORY_BUTLER_APP_ID }}
          private-key: ${{ secrets.REPOSITORY_BUTLER_PEM }}
        
      - name: Run Release Please
        id: release
        uses: googleapis/release-please-action@v4
        with:
          # Use configuration files for settings
          config-file: .release-please-config.json
          manifest-file: .release-please-manifest.json
          # Use GitHub App token for better permissions and rate limiting
          token: ${{ steps.app-token.outputs.token }}

  # Trigger the existing release workflow when a release is created
  trigger-release:
    needs: release-please
    if: ${{ needs.release-please.outputs.release_created }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Trigger release workflow
        run: |
          echo "Release created: ${{ needs.release-please.outputs.tag_name }}"
          echo "The existing release.yml workflow will be triggered by the tag creation"